// Virtual `lunar-css/__theme__` module emit.
//
// Strategy: we materialize a real file under `<projectRoot>/.lunarcss/`
// (gitignorable) so Metro's resolver can return a `sourceFile` entry that
// points at it. Truly in-memory virtual modules require Metro internals that
// shift between versions; a generated file with content-hash comparison is
// the most stable cross-version contract.

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { FlatTokens } from './types.js'

export interface VirtualThemeEmitResult {
  filepath: string
  hash: string
  changed: boolean
}

const VIRTUAL_DIR_NAME = '.lunarcss'
const VIRTUAL_BASENAME = '__theme__.js'

export function generateThemeSource(tokens: FlatTokens): string {
  const entries = Object.keys(tokens)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(tokens[k])}`)
    .join(',\n')
  return `// AUTO-GENERATED by lunar-css/metro. Do not edit.
export const THEME_TOKENS = Object.freeze({
${entries}
})
`
}

export function emitVirtualTheme(
  projectRoot: string,
  tokens: FlatTokens,
): VirtualThemeEmitResult {
  const dir = join(projectRoot, VIRTUAL_DIR_NAME)
  const filepath = join(dir, VIRTUAL_BASENAME)
  const next = generateThemeSource(tokens)
  const hash = createHash('sha1').update(next).digest('hex').slice(0, 16)

  let changed = true
  if (existsSync(filepath)) {
    const prev = readFileSync(filepath, 'utf8')
    if (prev === next) changed = false
  } else {
    mkdirSync(dirname(filepath), { recursive: true })
  }
  if (changed) writeFileSync(filepath, next, 'utf8')

  return { filepath, hash, changed }
}
